# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json
kind: AIchorManifest
apiVersion: "0.2.3"
name: test
builder:
  image: test_image # UPDATE ME
  dockerfile: ./Dockerfile
  context: .
#UPDATE ME ichor
spec:
  operator: tf
  image: test_image
  command: "entrypoint.sh /aide-ds/run.sh"
  # command: "/usr/local/bin/entrypoint.sh /aide-ds/run.sh"
  types:
    Worker: # UPDATE ME
      count: 1
      resources:
        cpus: 8 #96 # 48 # 12 # 24 # 24 # 48 #  96 # optional: number of GPUs wanted
        ramRatio: 8 # total ram = ramRatio * cpus # mandatory (must be >= 2): RAM ratio wanted (in GB)
        # 4 CPUs per GPU for Quadro-RTX-4000
        shmSizeGB: 10
        accelerators:
          gpu: # mandatory (if gpus amount is > 0): gpu type wanted
            count: 1
            type: gpu # mig-3g.20gb #mig-3g.40gb #mig-3g.40gb # UPDATE ME mig-3g.40gb
            product: NVIDIA-H100-80GB-HBM3  # NVIDIA-A100-SXM4-80GB #
  debug:
      vscode:
        enabled: True # required
        path: "/aichor/code" # Optional, defaults to "code". Refer the absolute path of the binary if not findable in $PATH
        provider: "github" # Optional, vscode tunnel provider. Options are "github" or "microsoft", defaults to "github" 