data_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- asim_aims_ac_za
- workspace
- aide-agent
- data
- text-normalization-challenge-english-language
desc_file: !!python/object/apply:pathlib.PosixPath
- /
- home
- asim_aims_ac_za
- workspace
- aide-agent
- data
- text-normalization-challenge-english-language
- description.md
goal: null
eval: null
log_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- asim_aims_ac_za
- workspace
- aide-agent
- logs
- __deepseek-chat+deepseek-chattext-normalization-challenge-english-language_Baseline_500_steps
log_level: DEBUG
workspace_dir: !!python/object/apply:pathlib.PosixPath
- /
- home
- asim_aims_ac_za
- workspace
- aide-agent
- workspaces
- __deepseek-chat+deepseek-chattext-normalization-challenge-english-language_Baseline_500_steps
competition_name: text-normalization-challenge-english-language
preprocess_data: true
copy_data: true
use_template: false
exp_name: __deepseek-chat+deepseek-chattext-normalization-challenge-english-language_Baseline_500_steps
inference_engine: vllm
exec:
  timeout: 600
  agent_file_name: runfile.py
  format_tb_ipython: false
agent:
  steps: 500
  time_limit: 36000
  k_fold_validation: 5
  expose_prediction: false
  data_preview: true
  convert_system_to_user: false
  obfuscate: false
  ITS_Strategy: Baseline
  code:
    model: deepseek-chat
    planner_model: deepseek-chat
    temp: 0.8
    max_new_tokens: 4096
    top_p: 0.9
    top_k: 50
    num_return_sequences: 1
  feedback:
    model: o4-mini-2025-04-16
    planner_model: ???
    temp: 0.5
    max_new_tokens: ???
    top_p: 1.0
    top_k: 40
    num_return_sequences: 1
  search:
    max_debug_depth: 50
    debug_prob: 0.65
    num_drafts: 12
wandb:
  enabled: true
  project: MLE_BENCH_AIDE_VM
  entity: asim_awad
  run_name: __deepseek-chat+deepseek-chattext-normalization-challenge-english-language_Baseline_500_steps
  log_code: true
  log_artifacts: true
