# path to the task data directory
data_dir: null

# either provide a path to a plaintext file describing the task
desc_file: null
# or provide the task goal (and optionally evaluation information) as arguments
goal: null
eval: null

log_dir: logs
log_level: INFO
workspace_dir: workspaces

# whether to unzip any archives in the data directory
preprocess_data: True
# whether to copy the data to the workspace directory (otherwise it will be symlinked)
# copying is recommended to prevent the agent from accidentally modifying the original data
copy_data: True

exp_name: null # a random experiment name will be generated if not provided

# settings for code execution
exec:
  timeout: 3600
  agent_file_name: runfile.py
  format_tb_ipython: False

# agent hyperparams
agent:
  # how many improvement iterations to run
  steps: 30
  # total time available to agent
  time_limit: 3600 #1 hour customised # 24 hrs (purely informational, implementation is user's resp)
  # whether to instruct the agent to use CV (set to 1 to disable)
  k_fold_validation: 5
  # whether to instruct the agent to generate a prediction function
  expose_prediction: False
  # whether to provide the agent with a preview of the data
  data_preview: True
  # whether to convert system messages into user messages
  convert_system_to_user: False
  # whether to obfuscate that we're doing kaggle
  obfuscate: False

  # LLM settings for coding
  code:
    model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
    # model: gpt-4-turbo
    temp: 0.5

  # LLM settings for evaluating program output / tracebacks
  feedback:
    # model: MFDoom/deepseek-r1-tool-calling:1.5b
    model: o3-mini
    # model: gpt-4-turbo
    temp: 0.5

  # hyperparameters for the tree search
  search:
    max_debug_depth: 5 
    debug_prob: 0.5
    num_drafts: 5

# W&B Logging Configuration
wandb:
  enabled: true             # Set to false to disable W&B logging
  project: "aide-ds"        # Your W&B project name
  entity: null              # Your W&B entity (username or team), null uses default
  run_name: null            # Optional: Set a specific run name, null generates one
  log_code: true            # Log the generated code for each step
  log_artifacts: true       # Log best solution code and submission as artifacts