_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 95
            "2":
                - 1
                - 11
                - 49
                - 55
                - 95
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "6": 4.44.2
            "8":
                - 2
                - 5
            "12": 0.19.9
            "13": linux-x86_64
agent:
    value:
        code:
            model: deepseek-r1:latest
            temp: 0.5
        convert_system_to_user: false
        data_preview: true
        expose_prediction: false
        feedback:
            model: o3-mini
            temp: 0.5
        k_fold_validation: 5
        obfuscate: false
        search:
            debug_prob: 0.5
            max_debug_depth: 5
            num_drafts: 1
        steps: 1
        time_limit: 3600
copy_data:
    value: true
data_dir:
    value: /home/asim/Desktop/aider/aide/example_tasks/house_prices
desc_file:
    value: null
eval:
    value: Use the RMSE metric between the logarithm of the predicted and observed values.
exec:
    value:
        agent_file_name: runfile.py
        format_tb_ipython: false
        timeout: 3600
exp_name:
    value: peculiar-ancient-harrier
goal:
    value: Predict the sales price for each house
log_dir:
    value: /home/asim/Desktop/aider/logs/peculiar-ancient-harrier
log_level:
    value: INFO
preprocess_data:
    value: true
wandb:
    value:
        enabled: true
        entity: null
        log_artifacts: true
        log_code: true
        project: my-aide-experiments
        run_name: peculiar-ancient-harrier
workspace_dir:
    value: /home/asim/Desktop/aider/workspaces/peculiar-ancient-harrier
